---
services:
  sonarqube:
    container_name: sonarqube
    image: sonarqube
    restart: unless-stopped
    environment: [SONAR_ES_BOOTSTRAP_DISABLE=true]
    ports: [9000:9000]
    stop_grace_period: 3600s
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
volumes:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:
