---
name: ci-sonarcloud
on:
  pull_request:
    branches: [development]
jobs:
  run-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18.12.0
          cache: npm
          cache-dependency-path: package-lock.json
      - run: npm install
      - run: npm test  # jest --coverage
      # Sonar cloud scan
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
